branch-defaults:
  master:
    environment: my-itachi
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: myt2micro
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Ruby 2.3 (Passenger
    Standalone)
  default_region: ap-southeast-1
  profile: eb-cli
  sc: git
